Repository bw-99/MAP, pull requests merged in 2025-03, with the labels that each got.

#18 enhancement: augmenting entity and relationship extraction for research papers
  graphrag/config/create_graphrag_config.py
  graphrag/config/models/graph_rag_config.py
  graphrag/config/models/sentence_reconstruction_config.py
  graphrag/index/create_pipeline_config.py
  graphrag/index/flows/reconstruct_sentence.py
  graphrag/index/operations/reconstruct_sentence/__init__.py
  graphrag/index/operations/reconstruct_sentence/plain_llm_strategy.py
  graphrag/index/operations/reconstruct_sentence/reconstruct_sentence.py
  graphrag/index/operations/reconstruct_sentence/sentence_reconstructor/__init__.py
  graphrag/index/operations/reconstruct_sentence/sentence_reconstructor/sentence_reconstructor.py
  graphrag/index/operations/reconstruct_sentence/typing.py
  graphrag/index/workflows/v1/create_base_text_units.py
  graphrag/prompts/index/sentence_reconstruction.py
  onepiece_rag/prompts/entity_extraction_with_reconstructed_sentence.txt
  onepiece_rag/prompts/evaluate_response.txt
  onepiece_rag/prompts/sentence_reconstruction_prompt.txt
  onepiece_rag/settings.yaml
Labels: enhancement

#22 fix: shifting indexing pipeline evaluation from absolute to relative grading
  graphrag/api/__init__.py
  graphrag/api/evaluate.py
  graphrag/cli/evaluate.py
  graphrag/cli/main.py
  graphrag/query/structured_search/global_search/search.py
  onepiece_rag/prompts/evaluate_graph.txt
  onepiece_rag/settings.yaml
Labels: enhancement, fix

#12 init : CI
  .github/workflows/ci.yml
  Dockerfile
  conftest.py
  util/test_file.py
Labels: ci/cd

#26 chore: precommit all files
  graphrag/api/evaluate.py
  graphrag/cli/evaluate.py
  graphrag/cli/main.py
  graphrag/config/models/sentence_reconstruction_config.py
  graphrag/evaluate/factory.py
  graphrag/index/operations/reconstruct_sentence/reconstruct_sentence.py
  graphrag/index/operations/reconstruct_sentence/sentence_reconstructor/sentence_reconstructor.py
  graphrag/index/workflows/v1/extract_graph.py
  graphrag/prompts/index/sentence_reconstruction.py
  graphrag/query/query_handler.py
  graphrag/query/structured_search/global_search/search.py
  onepiece_rag/prompts/entity_extraction_with_reconstructed_sentence.txt
  onepiece_rag/prompts/evaluate_graph.txt
  onepiece_rag/prompts/evaluate_response.txt
  onepiece_rag/prompts/sentence_reconstruction_prompt.txt
  onepiece_rag/prompts/summarize_descriptions.txt
  onepiece_rag/settings.yaml
  util/test_file.py
Labels: chore
